### ISSUE TITLE
Question: How to define devDependencies for nodejs

### ISSUE THREAD

**Issue by fabianmoronzirfas** [replit/upm#16]
Thank you for the great project. 👏 

One question: how do I define  `devDependencies` for nodejs?

**Comment by raxod502** [comment]
Currently, there is no such support directly through UPM. However, if you add a package to `devDependencies` manually using Yarn or NPM, then it will show up in `upm list`. This is in an effort to keep the abstractions as simple as possible -- every package manager is its own special little snowflake in terms of what groups and categories and metadata it has for dependencies, and we'd prefer to avoid going down the road of adding support for all of them.

**Comment by fabianmoronzirfas** [comment]
Thanks for the info. What about passing flags down to the specific manager. Like e.g. `npm run foo — —some-flag`

**Comment by raxod502** [comment]
I'm kind of inclined to say that we'd like to avoid this complexity as well. The problem is mitigated dramatically because UPM tells you exactly what commands it's running, so you can just run them yourself if you'd like to pass custom command-line options. That approach is not too user-unfriendly, and it will scale a _lot_ better to supporting all the kinds of customization that might be desired.
