### ISSUE TITLE
PNPM Support?

### ISSUE THREAD

**Issue by kaptcha0** [replit/upm#84]
There is already support for Yarn and NPM, I think PNPM would be attainable. I would be happy to implement it myself if I knew where to start.

**Comment by rohanrajpal** [comment]
+1, just paid for ghostwriter only to realise pnpm is not supported lmao. Anyhow happy to help make this supported soon!

**Comment by lafkpages** [comment]
PNPM is already supported.

**Comment by karlhorky** [comment]
@lafkpages any idea how to get the latest pnpm running on Replit? Would be great to have it work out of the box too, zero-config with new Replits...

**Comment by cdmistman** [comment]
@karlhorky ah, yeah, that one's annoying. easiest is to `npm install --save-dev pnpm`, or you can add `pkgs.nodePackages.pnpm` to `replit.nix`

i'll make sure all of the popular package managers (`npm`, `yarn`, `pnpm`, and `bun`) are available in the node nixmodule soon. i'll close this issue for now though, since that topic is unrelated to upm

**Comment by lafkpages** [comment]
> any idea how to get the latest pnpm version running on Replit in the fewest steps possible?

You could also use @DillonB07's template: [Nodejs w/ PNPM](https://replit.com/@DillonB07/Nodejs-with-PNPM).
It comes with `pnpm` installed, and uses PNPM for UPM aka the packager tool.

**Comment by DillonB07** [comment]
@karlhorky I've upgraded the nix channel used so it now has 8.5.1 which is the latest version available on nix channel 23.05

**Comment by karlhorky** [comment]
Thanks!
